<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>3.8.7</Version>
        <LangVersion>latest</LangVersion>
        <Title>Avalonia Controls - AJB</Title>
        <Description>Some controls for Avalonia: GroupBox, ComboBoxEx, TextBoxEx, RadioGroup, RadioCheckEnumGroup, SideBySideList and DropControl</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaXaml Remove="CustomTypeObjects\**" />
        <AvaloniaXaml Remove="TestAvControls.Desktop\**" />
        <AvaloniaXaml Remove="TestAvControls\**" />
        <AvaloniaXaml Remove="TestControls\**" />
        <Compile Remove="CustomTypeObjects\**" />
        <Compile Remove="TestAvControls.Desktop\**" />
        <Compile Remove="TestAvControls\**" />
        <Compile Remove="TestControls\**" />
        <EmbeddedResource Remove="CustomTypeObjects\**" />
        <EmbeddedResource Remove="TestAvControls.Desktop\**" />
        <EmbeddedResource Remove="TestAvControls\**" />
        <EmbeddedResource Remove="TestControls\**" />
        <None Remove="CustomTypeObjects\**" />
        <None Remove="TestAvControls.Desktop\**" />
        <None Remove="TestAvControls\**" />
        <None Remove="TestControls\**" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaXaml Remove="Themes\Fluent\EditWithDropControlStyles.axaml" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="AnimatedLinearBrush.cs" />
        <Compile Remove="Markup\CustomTypeBindingExtension.cs" />
        <Compile Remove="TooltipExtension.cs" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="AJBAvaloniaFluent.xaml" />
        <None Remove="AJBAvaloniaSimple.xaml" />
        <None Remove="AvaloniaControls_AJB.7z" />
        <None Remove="Images\folder_open24.png" />
        <None Remove="Images\search_24.png" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="AJBAvaloniaSimple.xaml" />
        <AvaloniaResource Include="AJBAvaloniaFluent.xaml" />
        <AvaloniaResource Include="Images\folder_open24.png" />
        <AvaloniaResource Include="Images\search_24.png" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.4" />
        <PackageReference Include="Avalonia.Skia" Version="12.0.4" />
        <PackageReference Include="Xaml.Behaviors.Interactivity" Version="12.0.0.1" />
    </ItemGroup>

    <Target Name="CopyPackage" AfterTargets="Pack">
        <Copy SourceFiles="$(PackageOutputPath)$(PackageId).$(PackageVersion).nupkg" DestinationFolder="$(ComponentLibraryPath)" />
    </Target>

    <ItemGroup>
        <UpToDateCheckInput Remove="Themes\Fluent\TextBoxEx.axaml" />
    </ItemGroup>

    <ItemGroup>
	    <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>